config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :stories do
    resources :idea
    resources :scenes do
      resources :comment
    end
  end

  get '/register' => 'account#new'
  post '/register' => 'account#create'
  get '/user/:id' => 'account#show', as: "user_page"
  get '/user/edit' => 'account#edit'
  put '/user/edit' => 'account#update'
  get '/users' => 'account#index'
  post '/role' => 'story_user#create'
  delete '/role' => 'story_user#destroy'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :ideas

  has_many :user_searches
  has_many :roles, through: :user_searches

  has_many :user_tags
  has_many :tags, through: :user_tags

  has_many :story_users
  has_many :stories, through: :story_users
  has_many :roles, through: :story_users

  has_many :comments

  def story_role?(story)
    story_user = story_users.where(:story => story)
    story_user.role
  end

  has_secure_password

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :account
  belongs_to :scene
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :account
  belongs_to :story
end

app/models/request.rb
class Request < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :user_searches
  has_many :story_searches
  has_many :story_users
end

app/models/scene.rb
class Scene < ActiveRecord::Base
  belongs_to :story
  has_many :comments
end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :scenes
  has_many :ideas

  has_many :story_users
  has_many :accounts, through: :story_users
  has_many :user_roles, through: :story_users, class_name: 'Role'

  has_many :story_tags
  has_many :tags, through: :story_tags

  has_many :story_searches
  has_many :roles, through: :story_searches

  def user_role?(user)
    story_user = story_users.where(:user => user)
    story_user.role
  end

end

app/models/story_search.rb
class StorySearch < ActiveRecord::Base
  belongs_to :story
  belongs_to :role
end

app/models/story_tag.rb
class StoryTag < ActiveRecord::Base
  belongs_to :story
  belongs_to :tag
end

app/models/story_user.rb
class StoryUser < ActiveRecord::Base
  belongs_to :story
  belongs_to :account
  belongs_to :role
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :story_tags
  has_many :user_tags
end

app/models/user_search.rb
class UserSearch < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/user_tag.rb
class UserTag < ActiveRecord::Base
  belongs_to :user
  belongs_to :tag
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/story_helper.rb
module StoryHelper
end

app/helpers/story_user_helper.rb
module StoryUserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookshelf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_header.html.erb
<title>Home</title>
<head>
     <meta charset='utf-8'>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <link rel='stylesheet' href='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/c\
	ss/bootstrap.min.css'>
  <script src='https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.j\
	  s'></script>
  <script src='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.\
	  js'></script>
   </head>
<body>
      <div class='container-fluid  bg-1'>
          <img src="http://imgc.allpostersimages.com/images/P-473-488-90/70/7022/8UUW100Z/posters/pop-ink-csa-images-octopus-wearing-crown.jpg"  height='50' width='50' >
         <font size = '6' style = 'Up:-50px'>Inklings</font>
         <nav class='navbar navbar-inverse '>
           <div class='container-fluid'>
             <ul class='nav navbar-nav'>
               <li><a href='/'>Home</a></li>
	       <li><%= link_to "Search Users", "/users" %></li>
	       <li><%= link_to "Search Stories", "/stories" %></li>
               <% if current_user %>
               <li>
		 <%= link_to "Account", user_page_path(current_user.id) %>
	       </li>
	       <li>
		 <%= link_to "Create Story", new_story_path %>
	       </li>
               <!--<li><a href='#'>Notebook</a></li>
               <li><a href='#'>Bookshelf</a></li>-->
	       <li><%= link_to "Logout", logout_path, method:"delete" %></li>
	       <% else %> 
               <li><%= link_to "Login", login_path %></li>
               <li><%= link_to "Register", register_path %></li>
              <%  end %>
	     </ul>	     
             <ul class='nav navbar-nav navbar-right'>
               <li><a href='#'>Search <span class='glyphicon glyphicon-search'></span></a></li>
             </ul>
           </div>
         </nav>
      </div>
    </body>
    

app/views/shared/_sidebar.html.erb
<html>
  <title>Home</title>  
  <div class="parentDiv" style ="position: absolute; right: 0 " >
    <div class="col-sm-4 right">
      <div class="container-fluid bg-1 text-center right" >
	<p>
          <div id = wrapper>
	    <br>
            <div class="container-fluid bg-2 text-center">
              Bookshelf
            </div>
	    <table class = "table table-hover">
	      <thead>
		<tr><th>Title</th>
		</tr>
	      </thead>
	      <tbody>
		<% @bookshelf.each do |book| %>
		<% book.each do |story| %>
		<tr>
		  <td><%= link_to story.title, story_path(story) %></td>
		</tr>
		<% end %>
		<% end %>
</table>	
          </div>
          <br>
</div></div></div></html>