config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :stories do
    resources :idea
    resources :scenes do
      resources :comment
    end
  end

  get '/register' => 'account#new'
  post '/register' => 'account#create'
  get '/user/:id' => 'account#show', as: "user_page"
  get '/user/edit' => 'account#edit'
  put '/user/edit' => 'account#update'
  get '/users' => 'account#index'
  post '/role' => 'story_user#create'
  delete '/role' => 'story_user#destroy'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :ideas

  has_many :user_searches
  has_many :roles, through: :user_searches

  has_many :user_tags
  has_many :tags, through: :user_tags

  has_many :story_users
  has_many :stories, through: :story_users
  has_many :roles, through: :story_users

  has_many :comments

  def story_role?(story)
    story_user = story_users.where(:story => story)
    story_user.role
  end

  has_secure_password

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :account
  belongs_to :scene
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :account
  belongs_to :story
end

app/models/request.rb
class Request < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :user_searches
  has_many :story_searches
  has_many :story_users
end

app/models/scene.rb
class Scene < ActiveRecord::Base
  belongs_to :story
  has_many :comments
end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :scenes
  has_many :ideas

  has_many :story_users
  has_many :accounts, through: :story_users
  has_many :user_roles, through: :story_users, class_name: 'Role'

  has_many :story_tags
  has_many :tags, through: :story_tags

  has_many :story_searches
  has_many :roles, through: :story_searches

  def user_role?(user)
    story_user = story_users.where(:user => user)
    story_user.role
  end

end

app/models/story_search.rb
class StorySearch < ActiveRecord::Base
  belongs_to :story
  belongs_to :role
end

app/models/story_tag.rb
class StoryTag < ActiveRecord::Base
  belongs_to :story
  belongs_to :tag
end

app/models/story_user.rb
class StoryUser < ActiveRecord::Base
  belongs_to :story
  belongs_to :account
  belongs_to :role
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :story_tags
  has_many :user_tags
end

app/models/user_search.rb
class UserSearch < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/user_tag.rb
class UserTag < ActiveRecord::Base
  belongs_to :user
  belongs_to :tag
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  def show
    @story = Story.find(params[:story_id])
    @scene = @story.scenes.find(params[:id])
  end

  def edit
    @story = Story.find(params[:story_id])
    @scene = @story.scenes.find(params[:id])
  end

  def create
    @story = Story.find(params[:story_id])
    @scene = @story.scenes.create()

#    if @scene.save
      redirect_to action: "edit", id: @scene.id
#    else
#      redirect_to @story
#    end
  end

  def update
    @story = Story.find(params[:story_id])
    @scene = @story.scenes.find(params[:id])
    
    @scene.update(scene_params)
      redirect_to @story
#    else
#      render 'edit'
#    end
  end
  
  def destroy
    @story = Story.find(params[:story_id])
    @scene = @story.scenes.find(params[:id])
    @scene.destroy

    redirect_to @story
  end

  private
    def scene_params
      params.require(:scene).permit(:body, :order, :show, :published)
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories = Story.all

    get_bookshelf
  end

  def show
     @story = Story.find(params[:id])

    get_bookshelf
  end

  def new
    @story = Story.new
    @people = @story.story_users.where(role_id: Role.where(description: "Writer").ids)
    @writers = @story.accounts.where(id: @people)

    get_bookshelf
  end

  def edit
    @story = Story.find(params[:id])
    @people = @story.story_users.where(role_id: Role.where(description: "Writer").ids)
    @writers = @story.accounts.where(id: @people)

    get_bookshelf
  end
  
  def create
    @account = Account.find(session[:user_id])
    @story = @account.stories.create(story_params)
#    @story_user = @account.story_users.create(story_user_params)

#    @story.text = @text

    @story_user = StoryUser.find_by(story_id: @story, account_id: @account)
    @story_user.role_id = Role.where(description: "Writer").first.id
    @story_user.approved = 1
    @story_user.save

    redirect_to @story
  end

  def update
    @story = Story.find(params[:id])

    if @story.update(story_params)
      redirect_to '/story/' + params[:id]
#      redirect_to "show", id: @story.id
    else
      redirect_to action: "edit", id: @story.id
    end
  end

  def destroy
  end

  def get_bookshelf
    if current_user
      @current = Account.find(session[:user_id])
      @bookshelf_ids = @current.story_users.where(role_id: Role.where(description: "Writer").ids)
      @notebook = @current.stories.where.not(id: @bookshelf_ids)
    end
  end

  private
  def story_params
    params.require(:story).permit(:title, :concept, :publish_status)
  end

  def story_user_params
    params.require(:story_user).permit(:story, :user, :role_id)
  end

end

app/controllers/story_controller.rb
class StoryController < ApplicationController
  def show
     @story = Story.find(params[:id])
  end

  def new
    @story = Story.new
#    @story_user = StoryUser.new
  end

  def edit
    
  end
  
  def create
    @account = Account.find(session[:user_id])
    @story = @account.stories.create(story_params)
#    @story_user = @account.story_users.create(story_user_params)

#    @story.text = @text

    @story_user = StoryUser.find_by(story_id: @story, account_id: @account)
    @story_user.role = Role.find_by(description: "Writer")
    @story_user.approved = 1

    redirect_to action: "show", id: @story.id
  end

  def update
  end

  def destroy
  end

  private
  def story_params
    params.require(:story).permit(:title, :concept, :publish_status)
  end

  def story_user_params
    params.require(:story_user).permit(:story, :user, :role)
  end

end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/story_helper.rb
module StoryHelper
end

app/helpers/story_user_helper.rb
module StoryUserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/stories/_form.html.erb
<%= form_for @story do |f| %>
<body>
  <% if @story.errors.any? %>
    <div id="error-explanation">
      <h2>
	<%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:
      </h2>
      <ul>
	<% @story.errors.full_messages.each do |msg| %>
	  <li><%= msg %></li>
	<% end %>
      </ul>
    </div>
  <% end %>
	
  <p>
    <%= f.text_field :title, :placeholder => "Working Title" %>
  </p>
  <p>
    <%= f.text_area :concept, cols: "170", rows: "17", :placeholder => "Concept/Summary" %>
  </p>
  <p>
    <% @writers.each do |user| %>
  <% if user.id == session[:user_id] %>
    <div class="story-user me">
	<%= user.username %>
	<%= link_to 'x', [story.story_user, story_user], method: :delete, data: {confirm: 'Are you sure you wish to stop writing this story?' } %>
      </div>
      <% else %>
    <div class="story-user">
      <%= user.username %>
    </div>
    <% end %>
    <% end %>
  </p>
  
<p>
  <% @writer_requests %>
  
</p>

<p>
  <%= f.submit "Save", class: "btn-submit" %>
</p>
</body>
<% end %>

app/views/stories/edit.html.erb
<%=render "shared/header" %>
<p1>

<%= render 'form' %>
</p1>

app/views/stories/index.html.erb
<%= render "shared/header" %>
<% @stories.each do |story| %>
  <h2 style="display:inline-block">
    <%= story.title %>
  </h2>
    <% if current_user %>
      <%= form_for :user_story, url: role_path do |f| %>
        <%= f.hidden_field :story_id, :value => story.id %>
        <%= f.hidden_field :account_id, :value => current_user.id %>
	<%= f.hidden_field :role_id, :value => 2 %>
        <%= f.submit "Follow"%>
      <% end %>
    <% end %>
  <p><%= story.concept %></p>
<% end %>

app/views/stories/new.html.erb
<%= render "shared/header" %>
<%= render 'form' %>

app/views/stories/show.html.erb
<%= render "shared/header" %>
<h1><%= @story.title %></h1>
<p><%= @story.concept %></p>

<h2>Scenes</h2>
<% @story.scenes.each do |scene| %>
    <p ><%= scene.body %></p>
<% end %>

<%= form_for([@story, @story.scenes.build]) do |f| %>
    <%= f.submit "Add Scene" %>
<% end %>

app/views/story/new.html.erb
<% if current_user %>
<%= "Hello, " << Account.find(session[:user_id]).username << "!" %>
<% end %>

<%= form_for :story do |f| %>
  <%= f.text_field :title, :placeholder => "Working Title" %>
  <br/>
  <%= f.text_area :concept, cols: "30", rows: "10", :placeholder => "Concept/Summary" %>
  <br/>
  <%= f.label "Who Can View:" %>
  <br/>
  <%= f.radio_button :publish_status, 0 %>
  <%= f.label :publish_status_0, "Writers only" %>
  <%= f.radio_button :publish_status, 1 %>
  <%= f.label :publish_status_1, "Approved editors" %>
  <%= f.radio_button :publish_status, 2 %>
  <%= f.label :publish_status_2, "Any user" %>
  <%= f.radio_button :publish_status, 3 %>
  <%= f.label :publish_status_3, "Everybody" %>
  <br/>
  <%= f.submit "Save", class: "btn-submit" %>
<% end %>

app/views/story/show.html.erb
<h1><%= @story.title %></h1>
<p><%= @story.concept %></p>